name: aramco_frontend
description: "Solution de gestion d'entreprise intégrée pour Aramco SA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.5+1

  # Navigation
  go_router: ^12.1.3

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.9
  table_calendar: ^3.1.1
  flutter_pdfview: ^1.3.2

  # Forms & Validation
  form_field_validator: ^1.1.0

  # Utils
  intl: 0.20.2
  logger: ^2.0.2+1
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Charts & Visualization
  fl_chart: ^0.65.0

  # Export & Documents
  pdf: ^3.10.4
  excel: ^4.0.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  permission_handler: ^11.1.0

  # Widgets
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  uuid: ^4.2.1

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
