import 'dart:io';
import 'dart:async';

/// Script pour corriger les fichiers générés automatiquement (.g.dart)
/// Ces fichiers sont générés par build_runner et peuvent être vides

class FixGeneratedFiles {
  int fixedFiles = 0;
  int totalFiles = 0;
  
  Future<void> startFixing() async {
    print('🔧 CORRECTION DES FICHIERS GÉNÉRÉS (.g.dart)');
    print('=' * 55);
    print('📅 Date: ${DateTime.now()}');
    print('🎯 Objectif: Corriger les fichiers .g.dart vides ou invalides');
    print('');
    
    // Phase 1: Identifier les fichiers .g.dart problématiques
    await identifyProblematicFiles();
    
    // Phase 2: Corriger les fichiers identifiés
    await fixFiles();
    
    // Phase 3: Valider les corrections
    await validateFixes();
    
    print('\n🎯 RAPPORT FINAL DE CORRECTION');
    print('=' * 55);
    print('✅ Fichiers corrigés: $fixedFiles/$totalFiles');
    
    if (fixedFiles > 0) {
      print('🎉 Correction des fichiers générés terminée avec succès !');
    } else {
      print('ℹ️ Aucun fichier à corriger détecté');
    }
  }
  
  Future<void> identifyProblematicFiles() async {
    print('🔍 PHASE 1: IDENTIFICATION DES FICHIERS PROBLÉMATIQUES');
    print('-' * 55);
    
    try {
      final directory = Directory('lib');
      List<String> problematicFiles = [];
      
      await for (final entity in directory.list(recursive: true)) {
        if (entity is File && entity.path.endsWith('.g.dart')) {
          totalFiles++;
          
          try {
            String content = await entity.readAsString();
            
            // Vérifier si le fichier est vide ou invalide
            if (content.trim().isEmpty || content.length < 50) {
              problematicFiles.add(entity.path);
              print('   ⚠️ Fichier problématique détecté: ${entity.path}');
            }
          } catch (e) {
            problematicFiles.add(entity.path);
            print('   ❌ Erreur lecture fichier: ${entity.path} - $e');
          }
        }
      }
      
      print('   📁 Fichiers .g.dart analysés: $totalFiles');
      print('   ⚠️ Fichiers problématiques: ${problematicFiles.length}');
      
    } catch (e) {
      print('   ❌ Erreur lors de l\'identification: $e');
    }
    
    print('✅ Phase 1 terminée');
    print('');
  }
  
  Future<void> fixFiles() async {
    print('🔧 PHASE 2: CORRECTION DES FICHIERS');
    print('-' * 35);
    
    try {
      final directory = Directory('lib');
      
      await for (final entity in directory.list(recursive: true)) {
        if (entity is File && entity.path.endsWith('.g.dart')) {
          await fixGeneratedFile(entity);
        }
      }
      
    } catch (e) {
      print('   ❌ Erreur lors de la correction: $e');
    }
    
    print('✅ Phase 2 terminée');
    print('');
  }
  
  Future<void> fixGeneratedFile(File file) async {
    try {
      String filePath = file.path;
      String fileName = filePath.split('\\').last;
      String baseFileName = fileName.replaceAll('.g.dart', '');
      
      // Créer un contenu de base pour les fichiers .g.dart
      String content = generateBaseGeneratedContent(baseFileName, filePath);
      
      // Écrire le contenu corrigé
      await file.writeAsString(content);
      fixedFiles++;
      
      print('   ✅ Fichier corrigé: $fileName');
      
    } catch (e) {
      print('   ❌ Erreur correction ${file.path}: $e');
    }
  }
  
  String generateBaseGeneratedContent(String baseFileName, String filePath) {
    // Déterminer le type de modèle basé sur le nom du fichier
    if (baseFileName.contains('employee')) {
      return generateEmployeeGeneratedContent();
    } else if (baseFileName.contains('order')) {
      return generateOrderGeneratedContent();
    } else if (baseFileName.contains('product')) {
      return generateProductGeneratedContent();
    } else if (baseFileName.contains('supplier')) {
      return generateSupplierGeneratedContent();
    } else if (baseFileName.contains('permission')) {
      return generatePermissionGeneratedContent();
    } else if (baseFileName.contains('tax')) {
      return generateTaxGeneratedContent();
    } else {
      return generateGenericGeneratedContent(baseFileName);
    }
  }
  
  String generateEmployeeGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'employee.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Employee _\$EmployeeFromJson(Map<String, dynamic> json) => Employee(
      id: json['id'] as int?,
      firstName: json['first_name'] as String,
      lastName: json['last_name'] as String,
      email: json['email'] as String,
      phone: json['phone'] as String?,
      department: json['department'] as String?,
      position: json['position'] as String?,
      salary: (json['salary'] as num?)?.toDouble(),
      hireDate: json['hire_date'] == null
          ? null
          : DateTime.parse(json['hire_date'] as String),
      isActive: json['is_active'] as bool? ?? true,
    );

Map<String, dynamic> _\$EmployeeToJson(Employee instance) => <String, dynamic>{
      'id': instance.id,
      'first_name': instance.firstName,
      'last_name': instance.lastName,
      'email': instance.email,
      'phone': instance.phone,
      'department': instance.department,
      'position': instance.position,
      'salary': instance.salary,
      'hire_date': instance.hireDate?.toIso8601String(),
      'is_active': instance.isActive,
    };
''';
  }
  
  String generateOrderGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'order.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Order _\$OrderFromJson(Map<String, dynamic> json) => Order(
      id: json['id'] as int?,
      orderNumber: json['order_number'] as String,
      customerId: json['customer_id'] as int,
      totalAmount: (json['total_amount'] as num?)?.toDouble() ?? 0.0,
      status: json['status'] as String?,
      orderDate: json['order_date'] == null
          ? null
          : DateTime.parse(json['order_date'] as String),
      deliveryDate: json['delivery_date'] == null
          ? null
          : DateTime.parse(json['delivery_date'] as String),
      notes: json['notes'] as String?,
    );

Map<String, dynamic> _\$OrderToJson(Order instance) => <String, dynamic>{
      'id': instance.id,
      'order_number': instance.orderNumber,
      'customer_id': instance.customerId,
      'total_amount': instance.totalAmount,
      'status': instance.status,
      'order_date': instance.orderDate?.toIso8601String(),
      'delivery_date': instance.deliveryDate?.toIso8601String(),
      'notes': instance.notes,
    };
''';
  }
  
  String generateProductGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _\$ProductFromJson(Map<String, dynamic> json) => Product(
      id: json['id'] as int?,
      name: json['name'] as String,
      description: json['description'] as String?,
      price: (json['price'] as num?)?.toDouble() ?? 0.0,
      category: json['category'] as String?,
      stock: json['stock'] as int? ?? 0,
      isActive: json['is_active'] as bool? ?? true,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
    );

Map<String, dynamic> _\$ProductToJson(Product instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'price': instance.price,
      'category': instance.category,
      'stock': instance.stock,
      'is_active': instance.isActive,
      'created_at': instance.createdAt?.toIso8601String(),
    };
''';
  }
  
  String generateSupplierGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'supplier.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Supplier _\$SupplierFromJson(Map<String, dynamic> json) => Supplier(
      id: json['id'] as int?,
      name: json['name'] as String,
      contactPerson: json['contact_person'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      address: json['address'] as String?,
      isActive: json['is_active'] as bool? ?? true,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
    );

Map<String, dynamic> _\$SupplierToJson(Supplier instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'contact_person': instance.contactPerson,
      'email': instance.email,
      'phone': instance.phone,
      'address': instance.address,
      'is_active': instance.isActive,
      'created_at': instance.createdAt?.toIso8601String(),
    };
''';
  }
  
  String generatePermissionGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'permission.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Permission _\$PermissionFromJson(Map<String, dynamic> json) => Permission(
      id: json['id'] as int?,
      name: json['name'] as String,
      description: json['description'] as String?,
      resource: json['resource'] as String?,
      action: json['action'] as String?,
      isActive: json['is_active'] as bool? ?? true,
    );

Map<String, dynamic> _\$PermissionToJson(Permission instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'resource': instance.resource,
      'action': instance.action,
      'is_active': instance.isActive,
    };
''';
  }
  
  String generateTaxGeneratedContent() {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of 'tax.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Tax _\$TaxFromJson(Map<String, dynamic> json) => Tax(
      id: json['id'] as int?,
      name: json['name'] as String,
      rate: (json['rate'] as num?)?.toDouble() ?? 0.0,
      description: json['description'] as String?,
      isActive: json['is_active'] as bool? ?? true,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
    );

Map<String, dynamic> _\$TaxToJson(Tax instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'rate': instance.rate,
      'description': instance.description,
      'is_active': instance.isActive,
      'created_at': instance.createdAt?.toIso8601String(),
    };
''';
  }
  
  String generateGenericGeneratedContent(String baseFileName) {
    return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner

part of '$baseFileName.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

// Generic generated content for $baseFileName
// This is a placeholder to prevent compilation errors
// You may need to run build_runner to generate proper serialization code
''';
  }
  
  Future<void> validateFixes() async {
    print('✅ PHASE 3: VALIDATION DES CORRECTIONS');
    print('-' * 40);
    
    try {
      final directory = Directory('lib');
      int validFiles = 0;
      
      await for (final entity in directory.list(recursive: true)) {
        if (entity is File && entity.path.endsWith('.g.dart')) {
          try {
            String content = await entity.readAsString();
            
            if (content.trim().isNotEmpty && content.length > 100) {
              validFiles++;
            }
          } catch (e) {
            print('   ❌ Erreur validation ${entity.path}: $e');
          }
        }
      }
      
      print('   📁 Fichiers .g.dart valides: $validFiles/$totalFiles');
      
    } catch (e) {
      print('   ❌ Erreur lors de la validation: $e');
    }
    
    print('✅ Phase 3 terminée');
    print('');
  }
}

void main() async {
  final fixer = FixGeneratedFiles();
  await fixer.startFixing();
}
